/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Column: typeof import('./src/components/ColumnComponent.vue')['default']
    ColumnComponent: typeof import('./src/components/ColumnComponent.vue')['default']
    CreateDialog: typeof import('./src/components/CreateDialog.vue')['default']
    Frame: typeof import('./src/components/Frame.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
